services:

  # =========================
  # DATABASES
  # =========================

  postgres-course:
    image: postgres:17
    container_name: postgres-course
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_course_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U course_user -d course_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lms-network

  postgres-user:
    image: postgres:17
    container_name: postgres-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lms-network

  postgres-enrollment:
    image: postgres:17
    container_name: postgres-enrollment
    environment:
      POSTGRES_DB: enrollment_db
      POSTGRES_USER: enrollment_user
      POSTGRES_PASSWORD: enrollment_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_enrollment_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U enrollment_user -d enrollment_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lms-network

  postgres-reporting:
    image: postgres:17
    container_name: postgres-reporting
    environment:
      POSTGRES_DB: reporting_db
      POSTGRES_USER: reporting_user
      POSTGRES_PASSWORD: reporting_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_reporting_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reporting_user -d reporting_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lms-network

  # =========================
  # KAFKA
  # =========================

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - lms-network

  # =========================
  # REDIS
  # =========================

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lms-network

  # =========================
  # MINIO
  # =========================

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - lms-network

  # =========================
  # USER SERVICE
  # =========================

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      DB_URL: jdbc:postgresql://postgres-user:5432/userdb
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8085:8080"
    depends_on:
      postgres-user:
        condition: service_healthy
    networks:
      - lms-network

  # =========================
  # COURSE SERVICE
  # =========================

  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile
    container_name: course-service
    environment:
      SERVER_PORT: 8082
      DB_URL: jdbc:postgresql://postgres-course:5432/course_db
      DB_USERNAME: course_user
      DB_PASSWORD: course_password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      JWT_SECRET: mySecretKeyForJwtAuthentication123456789
    ports:
      - "8082:8082"
    depends_on:
      postgres-course:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - lms-network

  # =========================
  # ENROLLMENT SERVICE
  # =========================

  enrollment-service:
    build:
      context: ./enrollment-service
      dockerfile: Dockerfile
    container_name: enrollment-service
    environment:
      SERVER_PORT: 8083
      DB_URL: jdbc:postgresql://postgres-enrollment:5432/enrollment_db
      DB_USERNAME: enrollment_user
      DB_PASSWORD: enrollment_password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8083"
    depends_on:
      postgres-enrollment:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - lms-network

  # =========================
  # REPORTING SERVICE
  # =========================

  reporting-service:
    build:
      context: ./reporting-service
      dockerfile: Dockerfile
    container_name: reporting-service
    environment:
      SERVER_PORT: 8086
      DB_URL: jdbc:postgresql://postgres-reporting:5432/reporting_db
      DB_USERNAME: reporting_user
      DB_PASSWORD: reporting_password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8086:8086"
    depends_on:
      postgres-reporting:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - lms-network

  # =========================
  # API GATEWAY
  # =========================

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - user-service
      - course-service
      - enrollment-service
      - reporting-service
    networks:
      - lms-network

# =========================
# VOLUMES
# =========================

volumes:
  postgres_course_data:
  postgres_user_data:
  postgres_enrollment_data:
  postgres_reporting_data:
  kafka_data:
  minio_data:
  redis_data:

# =========================
# NETWORK
# =========================

networks:
  lms-network:
    driver: bridge